color: null
description: null
fieldLayouts:
  bc25b190-bf51-4927-b010-63a59aa94476:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-03T11:11:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 51b89036-b57c-4892-aefb-56f15d5d945c # Accordion Items
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd447a2e-2628-4693-9361-08dad4567455
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 82334105-4a9a-48c1-9351-7e6bb0bc643f
        userCondition: null
handle: accordion
hasTitleField: false
icon: circle-plus
name: Accordion
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
