color: null
description: null
fieldLayouts:
  76f64cf0-b343-443f-8369-0cc8b1048137:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-02T13:43:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 21969370-50f4-4772-bb0d-01e56f327ba8 # Columns
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4ca75f7-d65d-4652-a599-b663f6badee2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-03T16:11:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b708e87e-9fc1-421a-9be2-104ef715362c # Column Layout
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67d83d2d-71e6-4e78-919e-496a9dd5fffe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 15f8e427-91af-4446-b1d4-67d97e4c5ba5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-04T13:38:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7397cb77-355d-47eb-83b4-30f061ca415b # Vertical Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0509125-c78d-4066-9816-71f333895d7a
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: e38704ac-702a-40d6-84c5-096d26e34270
        userCondition: null
handle: columns
hasTitleField: false
icon: line-columns
name: Columns
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
