color: null
description: null
fieldLayouts:
  a373861e-d45c-49d1-bb4e-a59fc784f46a:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:4e1a2680-df71-45bf-8145-a0dfb191aeda'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-28T15:31:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d363d288-d9a6-466d-82f0-a0fdd9530d71 # Form
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e1a2680-df71-45bf-8145-a0dfb191aeda
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 02741d23-0555-45d4-afc4-1292d6aab8f7
        userCondition: null
handle: form
hasTitleField: false
icon: input-text
name: Form
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
