color: null
description: null
fieldLayouts:
  62767917-9438-4429-a8a3-8a2938c3f86e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T12:15:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 24905e06-d0a8-486d-b05e-2d1128c9230e # Social Profiles
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f43f8835-124b-43dd-b7a8-371a09d22f7d
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Information'
        uid: b4db85a8-4380-498c-ac47-13ad224010f1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-04T10:58:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aff5ab29-35f9-43c1-bfc1-8419394f1987 # Text Content
            handle: callToAction
            instructions: null
            label: 'Call to Action'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b6cba30-43c8-492d-a620-5afcef521d07
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-04T10:58:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d363d288-d9a6-466d-82f0-a0fdd9530d71 # Form
            handle: newsletterForm
            instructions: null
            label: 'Newsletter Form'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d72ae85-717a-4b33-8b9c-d03bccd7ff81
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T12:15:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f01ab0c4-931a-46aa-bcec-67b6c6941e21 # Plain Text
            handle: copyrightNotice
            instructions: 'Use the `:year` and `:siteName` placeholders to inject the current year and site name.'
            label: 'Copyright Notice'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b64e7b56-9f77-4b06-bdf8-f13dc9cf2d34
            userCondition: null
            warning: null
            width: 100
        name: Footer
        uid: 8e03d624-bb85-4e17-8295-a092043dfb23
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-23T14:36:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ea252716-954a-4e85-b183-4852be96df43 # Tags
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54a17121-4f87-4293-8897-f48da62dcdeb
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 6298d91d-38cb-4b99-8310-c0932d994e0f
        userCondition: null
handle: globals
hasTitleField: false
icon: earth-africa
name: Globals
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
