color: null
description: null
fieldLayouts:
  a85e4189-c79d-4cf4-86f2-1296e286e38d:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:90d4ade3-7b5b-4514-89b3-f2d944f5b2e0'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-02T15:01:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d0c7900e-d61c-4839-a59e-70bb47358360 # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90d4ade3-7b5b-4514-89b3-f2d944f5b2e0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-03T13:48:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62083fb6-1a8c-49b9-9782-374ce3b3a7c8 # Rich Text (Basic)
            handle: caption
            instructions: null
            label: Caption
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 587c733d-1e08-4395-91a1-551d2ca7a5ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T15:01:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ae4f2361-8913-4891-ad95-3938347a1e55 # Aspect Ratio
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a83fa065-dd52-4db9-a6bf-62c2db30f961
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c0a5ab3-c7d3-4eea-ac03-470804bc56dd
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
