color: null
description: null
fieldLayouts:
  0abb94d7-b651-48ee-a52d-e252b8682713:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-02T21:19:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7b2e950b-64e1-4284-a6a1-110afd340922 # List Items
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d1cc1a5-de0e-4fbd-9ad7-aaacbde465a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 789f014d-3e69-4cad-b537-91f1af380d90
        userCondition: null
handle: list
hasTitleField: false
icon: list
name: List
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
