color: null
description: null
fieldLayouts:
  f4548303-08f8-4119-b7a8-9087de952b0b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-04T07:46:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d2885b6d-f853-4db9-af89-b465757a5fff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-04T07:48:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d0c7900e-d61c-4839-a59e-70bb47358360 # Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6899c676-854d-4d37-ab10-644cbe425c53
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-04T07:48:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3ed91472-4973-4997-8a82-57e4ff827e6e # Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d337340-65da-4ece-8bbe-7049659647b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 80e96264-f2e3-49b3-8d6b-65fad504e05d
        userCondition: null
handle: logo
hasTitleField: true
icon: apple
name: Logo
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
