color: null
description: null
fieldLayouts:
  8598c413-0b3e-4d2f-bde4-4b9f9bfd74e9:
    cardThumbAlignment: end
    cardView:
      - 'generatedField:0a237c9c-4735-459e-b3e3-24aa3d16102a'
    generatedFields:
      -
        handle: contentType
        name: 'Content Type'
        template: "{{ contentBlock.one.type.name ?? 'Unknown' }}"
        uid: 0a237c9c-4735-459e-b3e3-24aa3d16102a
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-04T08:56:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: 'Only used within the content management system to help identify blocks.'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 34c3f3cd-7c5c-4807-a721-38ef4bf2f6f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T14:46:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e913983b-447b-4aa9-bf9c-588f6ff2ca2f # Content Block
            handle: contentBlock
            instructions: null
            label: 'Content Block'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74fa451d-8c44-4324-bc31-f9538d110c1d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 43ee3413-4770-47f3-b0a4-3ba2ceb71bb6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-02T14:43:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e2c74420-bbaf-40c8-acf9-daf436a33bbd # Maximum Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30c819fc-3882-450c-a605-f29fa4739c31
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T14:43:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1414d7cb-fb98-4f48-88f2-e5b2401cf402 # Horizontal Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd350b17-9222-4309-a5b2-2d1a240c7c99
            userCondition: null
            warning: null
            width: 100
        name: Container
        uid: ca33b0b3-fcc2-4d78-b449-32aa57add704
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-02T14:43:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b15bb767-c33c-443c-8536-0b08e9e1d3df # Padding
            handle: paddingTop
            instructions: null
            label: 'Padding Top'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8783527-a924-4596-8705-7b002d85f0f4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T14:43:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b15bb767-c33c-443c-8536-0b08e9e1d3df # Padding
            handle: paddingBottom
            instructions: null
            label: 'Padding Bottom'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d5a3b61-0fee-45da-b835-391d82d3bfac
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: d288384d-44a1-41d9-aec1-89eb69d02a0a
        userCondition: null
handle: section
hasTitleField: true
icon: block
name: Section
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
