color: null
description: null
fieldLayouts:
  7c5c5cf2-5252-43c0-9ada-4a1e5acfa6ee:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:b8d62dbb-efd2-4060-b2f8-b3e5695598fd'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-02T11:57:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a34c1736-2104-4937-99c0-00f502185b62 # Media Type
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8d62dbb-efd2-4060-b2f8-b3e5695598fd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T11:57:07+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a34c1736-2104-4937-99c0-00f502185b62 # Media Type
                  layoutElementUid: b8d62dbb-efd2-4060-b2f8-b3e5695598fd
                  operator: in
                  uid: ce529da1-4903-4f92-9430-0fda9038f963
                  values:
                    - image
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: d0c7900e-d61c-4839-a59e-70bb47358360 # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81c15d28-c414-4db2-a526-a4db15cd017b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T12:02:42+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a34c1736-2104-4937-99c0-00f502185b62 # Media Type
                  layoutElementUid: b8d62dbb-efd2-4060-b2f8-b3e5695598fd
                  operator: in
                  uid: cfb1daf6-fd69-45e7-856f-d36915604c37
                  values:
                    - video
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7b4459c4-8611-49b4-abdf-99a0f4c7a646 # Video URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e536a45f-40b2-4279-8b25-71af5521d0f8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T17:12:10+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a34c1736-2104-4937-99c0-00f502185b62 # Media Type
                  layoutElementUid: b8d62dbb-efd2-4060-b2f8-b3e5695598fd
                  operator: in
                  uid: 6d1486fc-7b99-4ef2-99d6-41dbaec3aea1
                  values:
                    - video
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 728cd480-2381-49e3-9aab-e4af7f8306d0 # Video Tracks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f287f023-e095-4168-8dfb-d137c31eb09e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T14:32:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ae4f2361-8913-4891-ad95-3938347a1e55 # Aspect Ratio
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 552370c2-6ce9-4644-aa78-f1e79adb09b2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-23T19:32:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e10b1344-6730-4ebf-b792-fbc2e3a15e04 # Media Position
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b4bf69-f738-4df9-b00b-352275c2960a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-23T12:39:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7397cb77-355d-47eb-83b4-30f061ca415b # Vertical Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 560a8471-d090-4787-aa57-5a1097600f43
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-01-23T18:35:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aff5ab29-35f9-43c1-bfc1-8419394f1987 # Text Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 880eec01-7422-4f0d-8fa0-1784ea9fbec6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e5545267-423a-4364-aa58-913a6d4e8c87
        userCondition: null
handle: textAndMedia
hasTitleField: false
icon: photo-film
name: 'Text & Media'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
