color: null
description: null
fieldLayouts:
  5349098c-9207-4aaa-bc9c-7b7ee50c884f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-02T13:43:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b3db59d9-e848-437e-b500-49b5db1dc417
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T13:43:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aff5ab29-35f9-43c1-bfc1-8419394f1987 # Text Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22914ac7-7ff4-4f20-a3fd-924ad9a48e79
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a28422a2-262f-4420-9440-474bcac90404
        userCondition: null
handle: textColumn
hasTitleField: true
icon: align-justify
name: 'Text Column'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
