defaultPlacement: end
fieldLayouts:
  78f283fb-d50c-49ad-96f7-efc9c87b7b25:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-03T15:13:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 7bbf710e-b691-4a91-a419-3e883bbf7db1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-03T15:13:52+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 3c07b5aa-0037-40c0-891f-97d79aebe77e
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2025-07-03T15:13:52+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: e4d130f6-797d-40e3-be9a-441179e898ba
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: a2872aee-08eb-4d88-acb4-9bf73561c16f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-07-03T15:13:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 39c94e45-0c1d-4262-bead-823ceca25422
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-07-03T15:13:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 27257aec-5330-4e0d-9ad3-fd45c0e1b073
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2025-07-03T15:13:52+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: e9bb0aa4-f99a-4a22-938c-4aecf5a2100d
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: f6a4a92e-7f8f-4e65-87d2-cd71e2f866ef
        userCondition: null
handle: legalLinks
instructions: ''
maxNodes: null
name: 'Legal Links'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  fd532b74-9e46-4921-867f-79a80ef26fdf: # $CRAFT_SITE_NAME
    enabled: true
sortOrder: 3
structure:
  maxLevels: 1
  uid: 06ff144a-2b5c-43b5-bf23-a117b2ec9bef
