altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  78cfd22b-c0dd-4032-9d25-f0e496b88a9c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-02T11:54:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 56b16a62-69cf-4086-853a-cc2cc3e8e407
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f86ed93b-f18d-4926-80dd-cfed14bb93c2
        userCondition: null
fs: local
handle: files
name: Files
sortOrder: 2
subpath: files
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
