altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fd0ab186-27ef-4445-a8e8-7b09f38c2bc2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-02T11:54:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b0d91b8d-7533-46fd-a337-2e98cb319967
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-07-02T20:47:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: d5b1e33c-6ff9-43c6-a79c-b568996ee99e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f25db068-8ac4-43b8-819b-cf8b2d077e38
        userCondition: null
fs: local
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
