columnSuffix: null
handle: aspectRatio
instructions: null
name: 'Aspect Ratio'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '1:1'
        -
          - value
          - square
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4:3'
        -
          - value
          - photo
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '3:4'
        -
          - value
          - photo-portrait
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '16:9'
        -
          - value
          - video
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Pano
        -
          - value
          - pano
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Auto
        -
          - value
          - auto
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
