columnSuffix: null
handle: entryType
instructions: null
name: 'Entry Type'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
